### ISSUE TITLE
Your Podfile requires that the plugin `cocoapods-rome` be installed. Please install it and try installation again.

### ISSUE THREAD

**Issue by tonychan818** [CocoaPods/Rome#45] opened 2016-07-22 05:57 UTC
when run pod install,
it shows
Your Podfile requires that the plugin `cocoapods-rome` be installed. Please install it and try installation again.
any idea?

**Comment by neonichu** [comment] 2016-07-22 16:11
What's the output of `gem list --local|grep rome`? Do you see any errors printed on the console about the rome plugin failing to load?

**Comment by MickeyHub** [comment] 2016-08-20 06:04
I did encountered it just now, the reason is Load plugin error, because I use CocoaPods 1.0.1, not CocoaPods.1.1.0.beta

**Comment by castus** [comment] 2016-12-08 12:48
Still occurs, I'm using ```cocoapods (1.1.1)``` and ```cocoapods-rome (0.6.0)```
Any idea?

**Comment by mgrebenets** [comment] 2016-12-11 08:33
I can't get `cocoapods (1.1.1)` and `cocoapods-rome (0.7.0)` installed at the same time due to dependencies issue:

```
Bundler could not find compatible versions for gem "fourflusher":
  In snapshot (Gemfile.lock):
    fourflusher (= 2.0.1)

  In Gemfile:
    cocoapods (= 1.1.1) was resolved to 1.1.1, which depends on
      fourflusher (~> 2.0.1)

    cocoapods-rome (~> 0.7) was resolved to 0.7.0, which depends on
      fourflusher (~> 1.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by danielmhanover** [comment] 2017-01-15 14:32
+1

**Comment by jugutier** [comment] 2018-05-24 01:46
This doesn't seem like an issue anymore with cocoapods 1.5.2 & rome 1.0.0, should we close it?

**Comment by mgrebenets** [comment] 2018-05-25 05:36
Works OK now for versions `1.5.0` and `0.8.0` of CocoaPods and CocoaPod Rome respectively.

**Closed** 2018-05-25 05:56 UTC

**Comment by whalemare** [comment] 2019-03-29 06:01
Im my case it`s be not CocoaPods error, but my terminal environment.

After installing `gem` dependency and run `pod install` I will get this error each time.
But the cause of the error is not in the fact that the dependence is not established, but in the fact that it could **not be found**.

So, I am running this command for found more info about my dependency location:
 `gem info cocoapods-fix-react-native`

```
*** LOCAL GEMS ***
...some info
    Installed at: /usr/local/lib/ruby/gems/2.6.0
...some info
```

After that, I am looking my zesh profile by:
`open ~/.zshrc`

and add to it next line:
`export PATH="/usr/local/lib/ruby/gems/2.6.0/gems:$PATH"`

After that all works fine and `pod install` not cause errors.
